#!/usr/bin/env python3
"""
Seed union data for Launatrausti.

Sources:
- posting.is/en/employment-conditions/overview-of-trade-unions-and-wage-tables
- vr.is, efling.is, bhm.is, bsrb.is
- Web research March 2026
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.database import save_union

UNIONS = [
    {
        "name": "VR",
        "name_en": "VR — Store & Office Workers' Union",
        "federation": "ASÍ",
        "website": "https://www.vr.is",
        "sector": "Verslun og skrifstofa",
        "members": 37000,
        "fee_pct": 0.70,
        "sick_fund_pct": 1.00,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.30,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 270,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": 800000,
        "description": "Stærsta stéttarfélag verslunar- og skrifstofufólks á Íslandi. Stofnað 1920.",
        "benefits_summary": "Sjúkrasjóður (80% launa í 270 daga), orlofssjóður með sumarhúsum, starfsmenntasjóður, VR Varasjóður (sveigjanlegur styrktarsjóður), sérkjör og afslættir í gegnum 1819 Torgið, lögfræðiaðstoð, dánarbætur (800.000 kr á barn).",
        "wage_agreement_period": "2024-02 til 2028-01",
        "min_wage": 438000,
    },
    {
        "name": "Efling",
        "name_en": "Efling — General Workers' Union",
        "federation": "ASÍ",
        "website": "https://www.efling.is",
        "sector": "Almenn og sérhæfð störf",
        "members": 30000,
        "fee_pct": 0.70,
        "sick_fund_pct": 1.00,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.30,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 270,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": 600000,
        "description": "Stéttarfélag almennra og sérhæfðra starfsmanna á höfuðborgarsvæðinu. Greiddi 650M kr í styrki 2023.",
        "benefits_summary": "Sjúkrasjóður (80% launa), sumarhús víðs vegar um land, menntasjóður, orlofssjóður, orlofsheimilarekstur, reiknivélar fyrir laun/orlofsuppbót/desemberuppbót.",
        "wage_agreement_period": "2024-02 til 2028-01",
        "min_wage": 438000,
    },
    {
        "name": "SGS",
        "name_en": "SGS — Federation of General & Special Workers",
        "federation": "ASÍ",
        "website": "https://www.sgs.is",
        "sector": "Almenn og sérhæfð störf",
        "members": 53000,
        "fee_pct": 0.70,
        "sick_fund_pct": 1.00,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.30,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 270,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Samband 19 stéttarfélaga, fjölmennasta samtök launafólks á Íslandi. Fimm meginsviðin: matvæli og landbúnaður, bygging og mannvirki, þjónusta og ferðaþjónusta, iðnaður, og opinber þjónusta.",
        "benefits_summary": "Sjúkrasjóður, orlofssjóður, starfsmenntasjóður, sameiginlegur launataxti fyrir öll aðildarfélög.",
        "wage_agreement_period": "2024-02 til 2028-01",
        "min_wage": 438000,
    },
    {
        "name": "Samiðn",
        "name_en": "Samiðn — Federation of Skilled Workers",
        "federation": "ASÍ",
        "website": "https://www.samidn.is",
        "sector": "Iðnaðarmenn",
        "members": 12000,
        "fee_pct": 0.70,
        "sick_fund_pct": 1.00,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.30,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 270,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Samband iðnfélaga — vélvirkjar, hárgreiðslufólk, málmtæknimenn, byggingamenn, garðyrkjumenn, skipasmíðamenn.",
        "benefits_summary": "Sjúkrasjóður, orlofssjóður, starfsmenntasjóður, sameiginlegur launataxti.",
        "wage_agreement_period": "2024-02 til 2028-01",
        "min_wage": 438000,
    },
    {
        "name": "VM",
        "name_en": "VM — Marine Engineers & Metal Technicians",
        "federation": "ASÍ",
        "website": "https://www.vm.is",
        "sector": "Sjómenn og tæknimenn",
        "members": 3500,
        "fee_pct": 0.70,
        "sick_fund_pct": 1.00,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.30,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 270,
        "holiday_homes": 0,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Stéttarfélag vélstjóra og málmtæknimanna. Landsfélag.",
        "benefits_summary": "Sjúkrasjóður, starfsmenntasjóður, lögfræðiaðstoð.",
        "wage_agreement_period": "2024-02 til 2028-01",
        "min_wage": 480000,
    },
    {
        "name": "BHM",
        "name_en": "BHM — Association of Academics",
        "federation": "BHM",
        "website": "https://www.bhm.is",
        "sector": "Háskólamenntað fólk",
        "members": 18500,
        "fee_pct": 0.80,
        "sick_fund_pct": 0.65,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.40,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 180,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Bandalag háskólamanna — 24 aðildarfélög. Flestir starfa í opinbera geiranum. Háskólakennarar, náttúrufræðingar, félagsvísindamenn o.fl.",
        "benefits_summary": "Styrktarsjóður, orlofssjóður, starfsmenntunarsjóður, rannsóknarsjóður (háskólakennarar), lögfræðiaðstoð um kjaramál.",
        "wage_agreement_period": "2024-04 til 2028-03",
        "min_wage": 520000,
    },
    {
        "name": "BSRB",
        "name_en": "BSRB — Federation of State & Municipal Employees",
        "federation": "BSRB",
        "website": "https://www.bsrb.is",
        "sector": "Opinberir starfsmenn",
        "members": 22000,
        "fee_pct": 0.75,
        "sick_fund_pct": 0.80,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.35,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 240,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Bandalag starfsmanna ríkis og bæja. Opinberir starfsmenn með framhaldsskólamenntun.",
        "benefits_summary": "Sjúkrasjóður, orlofssjóður, starfsmenntunarsjóður, lögfræðiaðstoð. Ríkisstarfsmenn njóta betri uppsagnarfrests.",
        "wage_agreement_period": "2024-04 til 2028-03",
        "min_wage": 480000,
    },
    {
        "name": "KÍ",
        "name_en": "KÍ — Icelandic Teachers' Union",
        "federation": "KÍ",
        "website": "https://www.ki.is",
        "sector": "Kennarar",
        "members": 5500,
        "fee_pct": 0.85,
        "sick_fund_pct": 0.70,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.40,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 180,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Kennarasamband Íslands — grunnskólakennarar og leikskólakennarar.",
        "benefits_summary": "Sjúkrasjóður, orlofssjóður, starfsmenntunarsjóður, lögfræðiaðstoð, niðurgreiðsla á símenntun.",
        "wage_agreement_period": "2024-06 til 2028-05",
        "min_wage": 520000,
    },
    {
        "name": "SFR",
        "name_en": "SFR — State Employees' Association",
        "federation": "BSRB",
        "website": "https://www.sfr.is",
        "sector": "Ríkisstarfsmenn",
        "members": 8000,
        "fee_pct": 0.75,
        "sick_fund_pct": 0.80,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.35,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 240,
        "holiday_homes": 1,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Stéttarfélag í almannaþjónustu — starfsmenn ríkis og ríkisstofnana.",
        "benefits_summary": "Sjúkrasjóður, orlofssjóður, starfsmenntunarsjóður, lögfræðiaðstoð, betri uppsagnarfrestur ríkisstarfsmanna.",
        "wage_agreement_period": "2024-04 til 2028-03",
        "min_wage": 480000,
    },
    {
        "name": "Rafiðnaðarsamband Íslands",
        "name_en": "RSÍ — Electrical Workers' Federation",
        "federation": "ASÍ",
        "website": "https://www.rsi.is",
        "sector": "Rafiðnaðarmenn",
        "members": 4000,
        "fee_pct": 0.70,
        "sick_fund_pct": 1.00,
        "holiday_fund_pct": 0.25,
        "education_fund_pct": 0.30,
        "rehab_fund_pct": 0.10,
        "employer_pension_pct": 11.50,
        "employee_pension_pct": 4.00,
        "sick_pay_pct": 80,
        "sick_pay_days": 270,
        "holiday_homes": 0,
        "education_grants": 1,
        "death_benefit": None,
        "description": "Samband rafiðnaðarmanna á Íslandi. Rafvirkjar og rafeindavirkjar.",
        "benefits_summary": "Sjúkrasjóður, starfsmenntasjóður, lögfræðiaðstoð.",
        "wage_agreement_period": "2024-02 til 2028-01",
        "min_wage": 480000,
    },
]


def main():
    count = 0
    for union_data in UNIONS:
        save_union(union_data)
        count += 1
        print(f"  Saved: {union_data['name']} ({union_data.get('members', '?')} members)")

    print(f"\nSeeded {count} unions.")


if __name__ == "__main__":
    main()
